export const SUBSCRIBER_LOGIN_REQUEST = 'SUBSCRIBER_LOGIN_REQUEST'
export const SUBSCRIBER_LOGIN_SUCCESS = 'SUBSCRIBER_LOGIN_SUCCESS'
export const SUBSCRIBER_LOGIN_FAIL = 'SUBSCRIBER_LOGIN_FAIL'

export const SUBSCRIBER_LOGOUT = 'SUBSCRIBER_LOGOUT'

export const SUBSCRIBER_REGISTER_REQUEST = 'SUBSCRIBER_REGISTER_REQUEST'
export const SUBSCRIBER_REGISTER_SUCCESS = 'SUBSCRIBER_REGISTER_SUCCESS'
export const SUBSCRIBER_REGISTER_FAIL = 'SUBSCRIBER_REGISTER_FAIL'
