export const SUBSCRIBER_LOGIN_REQUEST = 'SUBSCRIBER_LOGIN_REQUEST'
export const SUBSCRIBER_LOGIN_SUCCESS = 'SUBSCRIBER_LOGIN_SUCCESS'
export const SUBSCRIBER_LOGIN_FAIL = 'SUBSCRIBER_LOGIN_FAIL'

export const SUBSCRIBER_LOGOUT = 'SUBSCRIBER_LOGOUT'
