# Generated by Django 3.2 on 2021-04-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210429_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
